In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define vocabulary size
voc_size = 10000

In [5]:
### One hot representation
one_hot_rep=[one_hot(words, voc_size) for words in sent]
one_hot_rep

[[8876, 3068, 9809, 4634],
 [8876, 3068, 9809, 9317],
 [8876, 9106, 9809, 246],
 [4396, 5625, 6279, 7887, 7256],
 [4396, 5625, 6279, 7887, 1044],
 [8167, 8876, 5774, 9809, 1703],
 [3403, 6779, 5471, 7887]]

In [7]:
## Word embedding repesentation
from tensorflow.keras.layers import Embedding 
# from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [12]:
sent_length=8
embedded_docs=pad_sequences(one_hot_rep, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 8876 3068 9809 4634]
 [   0    0    0    0 8876 3068 9809 9317]
 [   0    0    0    0 8876 9106 9809  246]
 [   0    0    0 4396 5625 6279 7887 7256]
 [   0    0    0 4396 5625 6279 7887 1044]
 [   0    0    0 8167 8876 5774 9809 1703]
 [   0    0    0    0 3403 6779 5471 7887]]


In [13]:
##feature representation
dim=10

In [14]:
## Create model
model = Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.compile('adam','mse')

2025-07-11 06:12:27.808335: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M3 Pro
2025-07-11 06:12:27.808484: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 18.00 GB
2025-07-11 06:12:27.808493: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 6.00 GB
2025-07-11 06:12:27.808708: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2025-07-11 06:12:27.809050: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


In [15]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [16]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 195ms/step


2025-07-11 06:15:27.778340: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:117] Plugin optimizer for device_type GPU is enabled.


array([[[ 0.04008509,  0.02832093,  0.04878101,  0.01572113,
         -0.02982315, -0.04851944, -0.04369882,  0.02443994,
          0.0059638 ,  0.04101935],
        [ 0.04008509,  0.02832093,  0.04878101,  0.01572113,
         -0.02982315, -0.04851944, -0.04369882,  0.02443994,
          0.0059638 ,  0.04101935],
        [ 0.04008509,  0.02832093,  0.04878101,  0.01572113,
         -0.02982315, -0.04851944, -0.04369882,  0.02443994,
          0.0059638 ,  0.04101935],
        [ 0.04008509,  0.02832093,  0.04878101,  0.01572113,
         -0.02982315, -0.04851944, -0.04369882,  0.02443994,
          0.0059638 ,  0.04101935],
        [ 0.04895855, -0.04695929, -0.02911696,  0.02520982,
         -0.02439896,  0.01605536, -0.03923155,  0.01901117,
         -0.0134467 , -0.01331465],
        [ 0.03579423, -0.01314446,  0.01488168, -0.0026217 ,
          0.03737228,  0.02327147,  0.0026065 , -0.01311885,
          0.03220752, -0.04723945],
        [ 0.01653901, -0.0246666 ,  0.03465729,  0.0

In [17]:
embedded_docs[0]

array([   0,    0,    0,    0, 8876, 3068, 9809, 4634], dtype=int32)

In [18]:
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 11ms/step
[[ 0.04008509  0.02832093  0.04878101  0.01572113 -0.02982315 -0.04851944
  -0.04369882  0.02443994  0.0059638   0.04101935]
 [ 0.04008509  0.02832093  0.04878101  0.01572113 -0.02982315 -0.04851944
  -0.04369882  0.02443994  0.0059638   0.04101935]
 [ 0.04008509  0.02832093  0.04878101  0.01572113 -0.02982315 -0.04851944
  -0.04369882  0.02443994  0.0059638   0.04101935]
 [ 0.04008509  0.02832093  0.04878101  0.01572113 -0.02982315 -0.04851944
  -0.04369882  0.02443994  0.0059638   0.04101935]
 [ 0.04895855 -0.04695929 -0.02911696  0.02520982 -0.02439896  0.01605536
  -0.03923155  0.01901117 -0.0134467  -0.01331465]
 [ 0.03579423 -0.01314446  0.01488168 -0.0026217   0.03737228  0.02327147
   0.0026065  -0.01311885  0.03220752 -0.04723945]
 [ 0.01653901 -0.0246666   0.03465729  0.02819493  0.0063339   0.0120704
   0.00223341  0.00457009  0.02366206  0.0341008 ]
 [-0.03756753 -0.04819441  0.00537108  0.0051433   0.02728419  0.02219539


In [19]:
print(model.predict(embedded_docs)[0][0])

1/1 [==============================] - 0s 13ms/step
[ 0.04008509  0.02832093  0.04878101  0.01572113 -0.02982315 -0.04851944
 -0.04369882  0.02443994  0.0059638   0.04101935]
